# Deploy Lambda function through CI/CD
name: Deploy Lambda Function

on:
  push:
    branches:
      - main

jobs:
  deploy_lambda_function:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3

      - name: Set up SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: AKIAWUZX2PY55NHQO24N
          aws-secret-access-key: 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
          aws-region: us-east-1

      - name: Build SAM Application
        run: sam build

      - name: Deploy SAM Application
        run: echo "y" | sam deploy --stack-name sam-app --region us-east-1 --resolve-s3 --confirm-changeset false --capabilities CAPABILITY_IAM
